# Generated by Django 4.2.8 on 2024-03-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='extracted_dates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
